export {default as bgHeaderOfAbout} from './bg-header.png'
export {default as banner} from './banner.svg'
export {default as contactImg} from './contactImg.svg'
export {default as Banner2} from './banner2.svg'
export {default as Arrow} from './Arrow.svg'
export {default as bgContact} from './bg-contact.svg'